[build-system]
requires = ["setuptools>=65.5.0"]
build-backend = "setuptools.build_meta"

[project]
name = "orbitcore"
version = "0.1.0"
description = "A perspective- and illumination-invariant anomaly detection engine extending Anomalib."
readme = "README.md"
requires-python = ">=3.11.8"
license = { text = "Apache License 2.0" }

dependencies = [
    "torch>=2.5.1+cu121",
    "torchvision>=0.20.1+cu121",
    "anomalib>=2.2.0",
    "numpy>=2.2.6",
    "matplotlib>=3.10.7"
]

[project.urls]
"Homepage" = "https://github.com/ProgrammerGnome/orbitcore"
